package com.titan.core.datastore

import androidx.datastore.preferences.core.*

object PreferencesKeys {
    val THEME_MODE = stringPreferencesKey("theme_mode")
    val DYNAMIC_COLORS = booleanPreferencesKey("dynamic_colors")
    val FONT_SIZE = intPreferencesKey("font_size")
    val FONT_FAMILY = stringPreferencesKey("font_family")
    val TAB_SIZE = intPreferencesKey("tab_size")
    val WORD_WRAP = booleanPreferencesKey("word_wrap")
    val LINE_NUMBERS = booleanPreferencesKey("line_numbers")
    val MINIMAP = booleanPreferencesKey("minimap")
    val AUTO_SAVE = booleanPreferencesKey("auto_save")
    val AUTO_SAVE_INTERVAL = intPreferencesKey("auto_save_interval")
    val BRACKET_MATCHING = booleanPreferencesKey("bracket_matching")
    val CODE_FOLDING = booleanPreferencesKey("code_folding")
    val SPELL_CHECK = booleanPreferencesKey("spell_check")
    val HARD_WRAP = booleanPreferencesKey("hard_wrap")
    val VIM_MODE = booleanPreferencesKey("vim_mode")
    val SUGGESTIONS_ON = booleanPreferencesKey("suggestions_on")
    val ACTIVE_AI_PROVIDER_ID = stringPreferencesKey("active_ai_provider_id")
    val TERMINAL_SHELL = stringPreferencesKey("terminal_shell")
    val TERMINAL_FONT_SIZE = intPreferencesKey("terminal_font_size")
    val TERMINAL_THEME = stringPreferencesKey("terminal_theme")
    val GIT_USER_NAME = stringPreferencesKey("git_user_name")
    val GIT_USER_EMAIL = stringPreferencesKey("git_user_email")
    val BUILD_GRADLE_PATH = stringPreferencesKey("build_gradle_path")
    val BUILD_JAVA_HOME = stringPreferencesKey("build_java_home")
    val BUILD_SDK_PATH = stringPreferencesKey("build_sdk_path")
    val LANGUAGE = stringPreferencesKey("app_language")
    val FIRST_LAUNCH = booleanPreferencesKey("first_launch")
    val LAST_OPENED_PROJECT_ID = stringPreferencesKey("last_opened_project_id")
    val SIDEBAR_POSITION = stringPreferencesKey("sidebar_position")
    val CONSOLE_POSITION = stringPreferencesKey("console_position")
    val EXPERIMENTAL_FEATURES = booleanPreferencesKey("experimental_features")
    val CRASH_REPORTING = booleanPreferencesKey("crash_reporting")
    val ANALYTICS = booleanPreferencesKey("analytics")
}